---
services:
  valkey:
    container_name: hll-dev-valkey
    image: valkey/valkey:9
    restart: always
    volumes:
      - valkey-data:/data
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    networks:
      - hll-network

  hll:
    container_name: hll-dev-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=valkey
      - DB_PORT=6379
      - DB_PASSWORD=${VALKEY_PASSWORD}
    depends_on:
      - valkey
    networks:
      - hll-network

volumes:
  valkey-data:

networks:
  hll-network:
    driver: bridge
