---
services:
  valkey:
    container_name: hll-dev-valkey
    image: valkey/valkey:9
    restart: always
    volumes:
      - valkey-data:/data
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    ports:
      - "6379:6379"

  hll:
    container_name: hll-dev-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - valkey

volumes:
  valkey-data:
