---
services:
  valkey:
    container_name: hll-valkey
    image: valkey/valkey:9
    restart: always
    volumes:
      - valkey-data:/data
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    networks:
      - hll-net

  hll:
    container_name: hll-server
    image: ghcr.io/blccming/hidden-live-location-server:main
    restart: always
    depends_on:
      - valkey
    networks:
      - hll-net

  cloudflared:
    container_name: hll-cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - hll
    networks:
      - hll-net

volumes:
  valkey-data:

networks:
  hll-net:
    driver: bridge
