---
services:
  valkey:
    container_name: hll-valkey
    image: valkey/valkey:9
    restart: always
    volumes:
      - valkey-data:/data
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    networks:
      - hll-network

  hll:
    container_name: hll-server
    image: ghcr.io/blccming/hidden-live-location-server:latest
    restart: always
    environment:
      - LOGLEVEL=INFO
      - HOST=hll
      - PORT=8080
      - DB_HOST=valkey
      - DB_PORT=6379 # default valkey/redis port
      - DB_PASSWORD=${VALKEY_PASSWORD}
    depends_on:
      - valkey
    networks:
      - hll-network

  cloudflared: # make sure you configure the tunnel to point to hll:8080
    container_name: hll-cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - hll
    networks:
      - hll-network

volumes:
  valkey-data:

networks:
  hll-network:
    driver: bridge
